// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRYGVbCidgYxYEz8hQU8K6bOTsiPDOTgE',
    appId: '1:729972399696:web:734ee5ffd5ab9c780afb55',
    messagingSenderId: '729972399696',
    projectId: 'pixellove',
    authDomain: 'pixellove.firebaseapp.com',
    storageBucket: 'pixellove.firebasestorage.app',
    measurementId: 'G-BSD39NF12B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD48envl7jSZykRawdkPcCARc_NL2mD1MU',
    appId: '1:729972399696:android:389e39cd87fb63900afb55',
    messagingSenderId: '729972399696',
    projectId: 'pixellove',
    storageBucket: 'pixellove.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIbGapMvvregTzcdjJs86dShj_9Wnv2j0',
    appId: '1:729972399696:ios:278829e55db080780afb55',
    messagingSenderId: '729972399696',
    projectId: 'pixellove',
    storageBucket: 'pixellove.firebasestorage.app',
    iosClientId: '729972399696-0305tva3s76vpbj38hbktbht7q7i11q7.apps.googleusercontent.com',
    iosBundleId: 'com.pixellove.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIbGapMvvregTzcdjJs86dShj_9Wnv2j0',
    appId: '1:729972399696:ios:68ef4bcbcbe890f50afb55',
    messagingSenderId: '729972399696',
    projectId: 'pixellove',
    storageBucket: 'pixellove.firebasestorage.app',
    iosClientId: '729972399696-sh6363nhq03oqrbhnv2hmmnvmvvd3c6d.apps.googleusercontent.com',
    iosBundleId: 'com.example.pixelLove',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRYGVbCidgYxYEz8hQU8K6bOTsiPDOTgE',
    appId: '1:729972399696:web:89164f0215868b880afb55',
    messagingSenderId: '729972399696',
    projectId: 'pixellove',
    authDomain: 'pixellove.firebaseapp.com',
    storageBucket: 'pixellove.firebasestorage.app',
    measurementId: 'G-V6GM1ZCXBR',
  );
}
